### ISSUE TITLE
Changing the simulation module

### ISSUE THREAD

**Issue by KosumovicDenis** [KosumovicDenis/RSoftCAD.py#2]
Currently, there isn't a straightforward method to change the simulation module without modifying the Cad.py code directly. Admittedly, this aspect wasn't initially considered during the development process.

To make the necessary changes, you can modify the code starting from line 83 in the Cad.py file. The relevant section can be found [here](https://github.com/KosumovicDenis/RSoftCAD.py/blob/main/src/Cad.py#L83C1-L83C130). Depending on the desired module, you'll need to update line 83 with the appropriate value  based on the following mapping:

| Product     | Windows Name   |
|------------|----------------------|
| BeamPROP simulation tool | bsimw32.exe |
| FullWAVE simulation tool | fullwave.exe |
| BandSOLVE simulation tool | bandsolve.exe |
| GratingMOD simulation tool | grmod.exe |
| DiffractMOD simulation tool | dfmod.exe |
| FemSIM simulation tool | femsim.exe |
| ModePROP simulation tool | modeprop.exe |

It's important to note that I no longer have access to RSoft CAD, making it challenging for me to test these modifications. Please let me know if this approach works for you, and if not, kindly notify me so that we can collaborate on finding a solution.

**Comment by amanohatosan** [comment]
It works in RSoft-CAD, thanks for answering my question！
